name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SECTION_NAME: waka_athul
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 2
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
          TIME_RANGE: "last_30_days"
          SHOW_TIME: "True"
          SHOW_TOTAL: "True"
          SHOW_MASKED_TIME: "True"
          LANG_COUNT: 10
          #COMMIT_BY_ME: "True"
          #COMMIT_MESSAGE: "Updated by Shanelka Pramuditha"
